# Generated by Django 3.0.3 on 2020-02-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('state', models.CharField(choices=[('New', 'Нова'), ('Used', 'Підтримана (Б/У)')], max_length=225)),
                ('first_register', models.IntegerField()),
                ('transmision', models.CharField(choices=[('Automatic', 'Автомат'), ('Manual', 'Механіка'), ('Robot', 'Роботична')], max_length=225)),
                ('mileage', models.IntegerField()),
                ('power', models.IntegerField()),
                ('value', models.IntegerField()),
                ('color', models.CharField(max_length=225)),
                ('salon', models.CharField(choices=[('Fabric', 'Тканина'), ('Skin', 'Шкіра'), ('Skin/Alkantara', 'Шкіра/Альткантара')], max_length=225)),
                ('parktronick', models.CharField(choices=[('Nothing', 'Відсутні'), ('Front', 'Передні'), ('Back', 'Задні'), ('Camera', 'Камера')], max_length=225)),
                ('category', models.CharField(choices=[('Sedan', 'Седан'), ('Universal', 'Універсал'), ('Crossover', 'Кросовер'), ('Hatchback', 'Хетчбек'), ('Passenger van', 'Легковий фургон'), ('Special tech', 'Спец техніка')], max_length=225)),
                ('sity_flowrate', models.FloatField()),
                ('trace_flowrate', models.FloatField()),
                ('mixed_flowrate', models.FloatField()),
                ('detail', models.TextField()),
                ('isHidden', models.BooleanField(default=False, help_text='Поставте галочку для того что <b>приховати</b> цей автомобіль у списку', verbose_name='Приховати публікацію')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
            },
        ),
    ]
